#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Install Python dependencies
python3 -m pip install --requirement requirements.txt

pre-commit install

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

echo "Setup complete!"
